blank_issues_enabled: false
contact_links:
  - name: How do I do ___?
    url: https://community.home-assistant.io/
    about: Please ask and answer questions about template-entity-row in the Home Assistant Community forum.
  
